### ISSUE TITLE
Update Readme for this repo

### ISSUE THREAD

**Issue by rjohnson318** [rjohnson318/AzureLab#4]
Updated readme for this repo

**Comment by kevinlu1248** [comment]
Hey I'm one of the developers of Sweep. We're looking into this issue for you right now.

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by kevinlu1248** [comment]
Hey @rjohnson318 sorry for the delay. We fixed the issue (an issue with large tfstate files that broke the context window).

**Comment by rjohnson318** [comment]
@kevinlu1248 thanks alot for jumping on that so quickly!
